blog/urls.py
from django.conf.urls import url

from blog import views


urlpatterns = [
    url(r'^$', views.index, name='index'),
    url(r'^/(?P<blog_entry_id>\d+)/$', views.view_blog_entry,
        name='blog_entry'),
]

yogaopensource/urls.py
from django.conf.urls import include, url
from django.contrib import admin


urlpatterns = [
    url(r'^$', include('home.urls', namespace='home')),
    url(r'^blog', include('blog.urls', namespace='blog')),
    url(r'^ashtangayoga/', include('ashtangayoga.urls',
                                   namespace='ashtangayoga')),
    url(r'^yogaunterricht/', include('yogaunterricht.urls',
                                     namespace='yogaunterricht')),
    url(r'^admin/', admin.site.urls),
    url('^markdown/', include('django_markdown.urls')),
]

blog/models.py
from django.db import models
from django.contrib.auth.models import User

# Create your models here.


# class BlogEntry(models.Model):
#     title = models.CharField(max_length=350)
#     text = models.TextField()
#     date = models.DateTimeField()
#     author = models.ForeignKey(User)

#     def __str__(self):
#         return self.title

#     def get_title_preview(self):
#         title = self.title
#         return title if len(title) < 58 else (title[:58] + '...')

#     def get_text_preview(self):
#         text = self.text
#         return text if len(text) <= 255 else (text[:255] + '...')

blog/views.py
from django.http import HttpResponse
from django.template import RequestContext, loader
from django.shortcuts import get_object_or_404, render
from home.models import Text

# Create your views here.


def index(request):
    blog_entries = Text.objects.filter(
        text_type='blog_article').order_by('-created_date')
    sidebar_choices = Text.objects.filter(
        text_type='sidebar_choice', section='blog').order_by('-id')
    template = loader.get_template('blog/index.html')
    context = RequestContext(request, {
        'blog_entries': blog_entries,
    })
    return HttpResponse(template.render(context))


def view_blog_entry(request, blog_entry_id):
    blog_entry = get_object_or_404(Text, pk=blog_entry_id)
    template = loader.get_template('blog/blog_entry.html')
    context = RequestContext(request, {
        'blog_entry': blog_entry,
        })
    return HttpResponse(template.render(context))

blog/templates/blog/blog_entry.html
{% extends 'base.html' %}
{% block title %} {{ blog_entry.title }} {% endblock title %}
{% block content %}
{% if blog_entry %}
    <span class="blog_title">{{ blog_entry.title }}</span>
    <span style="display: block; text-align: right; padding-right: 20px"> {{ blog_entry.created_date }} </span>
    {{ blog_entry.render_text_markdown | safe }}
{% else %}
    <p>No blog entry content is available.</p>
{% endif %}
{% endblock content %}

blog/templates/blog/index.html
{% extends 'base.html' %}
{% block title %}Yoga-Artikel{% endblock title %}
{% block sidebar %}
    {% for sidebar_choice in sidebar_choices %}
        <a href="#{{ sidebar_choice.anchor }}">{{ sidebar_choice.text }}</a><br>
    {% endfor %}
{% endblock sidebar %}

{% block content %}
{% if blog_entries %}
    {% for blog_entry in blog_entries %}
        <a href="{% url 'blog:blog_entry' blog_entry.id %}">
            <div class="blog_preview">
                <span class="blog_title_preview"> {{ blog_entry.get_title_preview }} </span> <br>
                <span class="blog_date_preview"> {{ blog_entry.created_date }} </span> <br>
                <span class="blog_text_preview"> {{ blog_entry.get_text_preview_md | safe }}
            </div>
        </a>
    {% endfor %}
    <div style="clear: both"></div>
{% else %}
    <p>No blog entries are available.</p>
{% endif %}
{% endblock content %}